databases:
  - name: Recipes-project
    databaseName: recipes_project
    user: recipes_project_user

services:
  - type: web
    name: recipe-app-project
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipes_project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false